"""
CoatMenu - how a list becomes a real menu entry.

Two things have to exist for a menu to be reachable (and to take a hotkey
bound in 3DCoat - hover the entry and press END):

1. **a thin launcher script** - ``actions/menus/<Name>.py``. 3DCoat menu items
   point at a *file*, and one file cannot know which menu it belongs to, so each
   menu gets its own generated wrapper.
2. **a menu item** - ``Scripts/ExtraMenuItems/CoatMenu.xml`` (persistent, read at
   startup) *and* a runtime ``coat.ui.insertInMenu`` call (visible immediately).

Everything here is pure filesystem work with explicit paths, so it runs both
inside 3DCoat and from the standalone installer.
"""
from __future__ import annotations

import os
from xml.sax.saxutils import escape as xml_escape

from coatmenu.core.config import Menu, MenuConfig

MAIN_MENU_ID = "CoatMenu_Show"
MAIN_MENU_LABEL = "Show CoatMenu"
MAIN_SCRIPT_NAME = "CoatMenu_Show.py"


def entry_label(name: str) -> str:
    """The Scripts-menu name for one of our menus.

    Prefixed so CoatMenu's entries sit together in 3DCoat's Scripts list and are
    obvious at a glance; the menu keeps its own name everywhere else.
    """
    return " ".join(f"CoatMenu_{name}".split())


def legacy_hotkey_ids(config: MenuConfig) -> list[str]:
    """Ids earlier versions registered for these same menus.

    Before the terminology pass a menu's id was ``CoatMenu_List_<Name>``. Those
    entries are still in the *running* 3DCoat menu (rewriting the XML does not
    touch the live menu), which is how one menu ended up listed twice.
    """
    return [f"CoatMenu_List_{lst.slug}" for lst in config.menus]

EDITOR_MENU_ID = "CoatMenu_Editor"
EDITOR_MENU_LABEL = "Edit menus"
EDITOR_SCRIPT_NAME = "CoatMenu_Editor.py"

DOCTOR_MENU_ID = "CoatMenu_Doctor"
DOCTOR_MENU_LABEL = "Diagnostics (doctor)"
DOCTOR_SCRIPT_NAME = "CoatMenu_Doctor.py"

# Launcher files carry a prefix so 3DCoat's Scripts menu (which lists them by file
# name) keeps our entries together and clear of the user's own scripts. Only the
# file that launches a list is named this way - the list itself keeps its name, and
# the hotkey id is CoatMenu_<Name> (same as the launcher file).
LAUNCHER_PREFIX = "CoatMenu_"

_ENTRY_SCRIPT = '''"""CoatMenu list launcher - generated by CoatMenu, do not edit.

List: {name} (slug: {slug})
Regenerate from the CoatMenu editor; edits here are overwritten.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(os.path.dirname(_HERE))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)


def _schedule_self_removal() -> None:
    """Let the next click re-run this module.

    3DCoat executes a menu script as ``exec("import <module name>")``, so without
    this the second click would hit the import cache and do nothing. Two paths,
    because the extension's per-frame hook may not be running.
    """
    try:
        queue = getattr(sys, "_coatmenu_modules_to_clear", None)
        if queue is None:
            queue = set()
            sys._coatmenu_modules_to_clear = queue
        queue.add(__name__)
    except Exception:
        pass
    try:
        from PySide6.QtCore import QTimer
        QTimer.singleShot(0, lambda name=__name__: sys.modules.pop(name, None))
    except Exception:
        pass


def main() -> None:
    from coatmenu.core.log import log
    from coatmenu.core.show import show_list
    log("menu item: list {slug} (cExtension " +
        ("loaded)" if "CoatMenu" in sys.modules else "NOT loaded)"))
    show_list({slug!r}, script_path=os.path.abspath(__file__))


_schedule_self_removal()
main()
'''

_MENU_ENTRY = """\t<ExtraMenuItem>
\t\t<MenuPath>Scripts</MenuPath>
\t\t<MenuItem>{menu_id}</MenuItem>
\t\t<inRoom></inRoom>
\t\t<inSection></inSection>
\t\t<Command>script:{script}</Command>
\t</ExtraMenuItem>
"""

_MENU_XML = "<ClassArray.ExtraMenuItem>\n{entries}</ClassArray.ExtraMenuItem>\n"


def _posix(path: str) -> str:
    return str(path).replace("\\", "/")


def entry_script_path(entry_scripts_dir: str, slug: str) -> str:
    """Where a menu's launcher lives - prefixed, so the Scripts menu groups them."""
    return os.path.join(entry_scripts_dir, f"{LAUNCHER_PREFIX}{slug}.py")


def menu_slugs(config: MenuConfig) -> list[tuple[str, Menu]]:
    """``(slug, menu)`` for every menu, with the slugs made unique.

    Two menus can slugify to the same string: a name that is not ASCII used to
    collapse to ``menu`` for all of them (see ``config.slugify``), and punctuation
    can do it too (``Cut & Fill`` next to ``Cut__Fill``). Sharing a slug means
    sharing a launcher file *and* a hotkey id, so one file overwrote the other and
    the second menu was unreachable. A repeat gets a numeric suffix - in config
    order, so the slugs stay put as long as the menus keep their order.
    """
    used: dict[str, int] = {}
    out: list[tuple[str, Menu]] = []
    for menu in config.menus:
        base = menu.slug
        seen = used.get(base, 0)
        used[base] = seen + 1
        out.append((base if not seen else f"{base}-{seen + 1}", menu))
    return out


def menu_ids(config: MenuConfig) -> list[tuple[str, Menu]]:
    """``(command id, menu)`` - what 3DCoat knows each menu by, and it is unique.

    One source of truth for the id: the launcher file name, the entry 3DCoat
    registers, the hotkey id and the key lookup all come from here. Two names that
    slugify alike (``Cut & Fill`` next to ``Cut__Fill``) get distinct ids; sharing
    one would mean sharing a hotkey binding and an entry.
    """
    return [(f"{LAUNCHER_PREFIX}{slug}", lst) for slug, lst in menu_slugs(config)]


def find_menu(config: MenuConfig, key: str):
    """The menu a launcher, a command id or a name refers to.

    ``config.find`` matches ``Menu.slug``, which is not the unique one: for two
    names that slugify alike it is the *same* string for both, so the second
    menu's launcher (``show_list('Cut_Fill-2')``) would fall through to the wrong
    menu - or to none. The unique id wins here, then the plain lookup.
    """
    wanted = str(key or "").strip().lower()
    if not wanted:
        return None
    prefix = LAUNCHER_PREFIX.lower()
    for menu_id, menu in menu_ids(config):
        if wanted in (menu_id.lower(), menu_id.lower().replace(prefix, "", 1)):
            return menu
    return config.find(key)


def write_entry_scripts(config: MenuConfig, entry_scripts_dir: str) -> tuple[list[str], list[str]]:
    """(re)write one launcher per menu; delete launchers for menus that are gone.

    Also clears out launchers written before the prefix existed, so a menu does
    not show up twice in 3DCoat's Scripts menu.

    Returns ``(written, removed)`` absolute paths.
    """
    os.makedirs(entry_scripts_dir, exist_ok=True)
    pairs = menu_slugs(config)
    wanted = {slug for slug, _ in pairs}
    written: list[str] = []
    removed: list[str] = []

    for slug, lst in pairs:
        path = entry_script_path(entry_scripts_dir, slug)
        content = _ENTRY_SCRIPT.format(name=lst.name, slug=slug)
        if _read(path) != content:
            with open(path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(content)
            written.append(path)

    for name in os.listdir(entry_scripts_dir):
        if not name.endswith(".py") or name == "__init__.py":
            continue
        stem = name[:-3]
        if stem.startswith(LAUNCHER_PREFIX) and stem[len(LAUNCHER_PREFIX):] in wanted:
            continue  # ours, and the list is still there
        # Anything else here is a launcher for a list that is gone, or one from
        # the old unprefixed naming - the folder only ever holds our launchers.
        path = os.path.join(entry_scripts_dir, name)
        try:
            os.remove(path)
            removed.append(path)
        except OSError:
            pass

    return written, removed


def menu_entries(config: MenuConfig, extension_root: str, entry_scripts_dir: str,
                 include: str = "all") -> list[tuple[str, str, str]]:
    """(menu_id, label, script_path) - main entry, editor, doctor, every menu.

    ``include="fixed"`` leaves out the one-per-menu entries; the XML file holds
    those three, while the rest are inserted at runtime.
    """
    rows: list[tuple[str, str, str]] = [] if include == "menus" else [
        (
            MAIN_MENU_ID,
            MAIN_MENU_LABEL,
            os.path.join(extension_root, "actions", MAIN_SCRIPT_NAME),
        ),
        (
            EDITOR_MENU_ID,
            EDITOR_MENU_LABEL,
            os.path.join(extension_root, "actions", EDITOR_SCRIPT_NAME),
        ),
        (
            DOCTOR_MENU_ID,
            DOCTOR_MENU_LABEL,
            os.path.join(extension_root, "actions", DOCTOR_SCRIPT_NAME),
        ),
    ]
    if include == "fixed":
        return rows
    for menu_id, lst in menu_ids(config):
        slug = menu_id[len(LAUNCHER_PREFIX):]      # the unique one, not lst.slug
        rows.append((menu_id, entry_label(lst.name),
                     entry_script_path(entry_scripts_dir, slug)))
    return rows


def write_menu_xml(config: MenuConfig, extension_root: str, entry_scripts_dir: str, xml_path: str) -> str:
    """Write ``ExtraMenuItems/CoatMenu.xml`` (3DCoat needs absolute paths).

    Only the three fixed entries go in here. The one-per-menu entries are
    registered at runtime instead (``register_menus_via_api``) - writing them in
    both places would list every menu twice.
    """
    entries = "".join(
        _MENU_ENTRY.format(menu_id=xml_escape(menu_id), script=xml_escape(_posix(script)))
        for menu_id, _label, script in menu_entries(config, extension_root,
                                                    entry_scripts_dir, include="fixed")
    )
    os.makedirs(os.path.dirname(xml_path), exist_ok=True)
    content = _MENU_XML.format(entries=entries)
    with open(xml_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    return xml_path


def _xml_value(text: str, tag: str) -> str:
    """The text inside ``<tag>...</tag>``, or ``""`` when it is not there."""
    start = text.find(f"<{tag}>")
    if start < 0:
        return ""
    end = text.find(f"</{tag}>", start)
    if end < 0:
        return ""
    return text[start + len(tag) + 2:end].strip()


def persisted_menu_items(xml_path: str, extension_root: str) -> list[tuple[str, str]]:
    """``(menu_id, path)`` for the item files 3DCoat writes beside our own.

    3DCoat persists every runtime ``insertInMenu`` call as its own
    ``ExtraMenuItems/<id>.xml``. Nothing removes one when the menu behind it is
    deleted, so the entry is read back at every start and the menu never leaves
    the Scripts list. Only files naming a command *inside this extension* are
    returned - a neighbour's file in the same folder is not ours to touch.
    """
    folder = os.path.dirname(xml_path)
    try:
        names = sorted(os.listdir(folder))
    except OSError:
        return []
    ours = os.path.normcase(os.path.abspath(extension_root))
    found: list[tuple[str, str]] = []
    for name in names:
        if name == os.path.basename(xml_path) or not name.endswith(".xml"):
            continue
        text = _read(os.path.join(folder, name))
        script = _xml_value(text, "Command")
        if script.lower().startswith("script:"):
            script = script[len("script:"):]
        if not script or not os.path.normcase(os.path.abspath(script)).startswith(ours):
            continue                 # written for something that is not ours
        found.append((_xml_value(text, "MenuItem") or name[:-4],
                      os.path.join(folder, name)))
    return found


def prune_persisted_menu_items(config: MenuConfig, extension_root: str,
                               entry_scripts_dir: str,
                               xml_path: str) -> tuple[list[str], list[str]]:
    """Delete 3DCoat's own item files for menus that are no longer in the config.

    A menu deleted in the editor loses its config row and its launcher, but the
    file 3DCoat wrote for its entry stayed - so the entry came back on every start
    and the menu could never be got rid of. The three fixed entries were listed
    twice for the same reason (``CoatMenu.xml`` carries them *and* 3DCoat wrote a
    file for the insertion). Returns ``(stale_ids, removed_paths)``: the ids that
    also have to come out of the *running* menu, and the files that were deleted.
    """
    live = {menu_id for menu_id, _l, _s in menu_entries(
        config, extension_root, entry_scripts_dir, include="menus")}
    fixed = {menu_id for menu_id, _l, _s in menu_entries(
        config, extension_root, entry_scripts_dir, include="fixed")}
    stale: list[str] = []
    removed: list[str] = []
    for menu_id, path in persisted_menu_items(xml_path, extension_root):
        if menu_id in live:
            continue
        try:
            os.remove(path)
        except OSError:
            continue
        removed.append(path)
        if menu_id not in fixed:     # the fixed three are carried by CoatMenu.xml
            stale.append(menu_id)
    return stale, removed


def sync(config: MenuConfig, extension_root: str, entry_scripts_dir: str, xml_path: str) -> dict:
    """Bring the launcher scripts and the menu XML in line with ``config``."""
    written, removed = write_entry_scripts(config, entry_scripts_dir)
    write_menu_xml(config, extension_root, entry_scripts_dir, xml_path)
    stale_ids, items_removed = prune_persisted_menu_items(
        config, extension_root, entry_scripts_dir, xml_path)
    return {
        "menus": len(config.menus),
        "scripts_written": written,
        "scripts_removed": removed,
        "menu_xml": xml_path,
        "extra_items_removed": items_removed,
        "extra_ids_removed": stale_ids,
    }


def _read(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return ""
