"""Generate a global Qt stylesheet from a Theme.

All colours, spacing and fonts are derived directly from the
``Theme`` data model — no hard-coded literals.
"""
from __future__ import annotations


from ported.lks_utils.theme.theme import Theme
from ported.lks_utils.theme.palette import Palette
from ported.lks_utils.theme.metrics import Metrics
from ported.lks_utils.theme.typography import Typography


def _hex(color_obj: object) -> str:
    """Return 6-digit RRGGBB hex string suitable for QSS (strips '#' and alpha)."""
    full = color_obj.to_hex()  # type: ignore[union-attr]  → "#RRGGBBAA"
    return full[1:7]  # strip '#' and alpha → "RRGGBB"


def theme_to_qss(theme: Theme) -> str:
    """Return a global QSS stylesheet string derived entirely from *theme*."""
    p: Palette = theme.palette
    m: Metrics = theme.metrics
    t: Typography = theme.typography

    # Shorthands used repeatedly
    bg = _hex(p.panel_bg)
    fg = _hex(p.text_primary)
    border = _hex(p.border)
    input_bg = _hex(p.input_bg)
    input_fg = _hex(p.input_fg)
    input_border = _hex(p.input_border)
    btn_bg = _hex(p.button_bg)
    btn_fg = _hex(p.button_fg)
    btn_hover = _hex(p.button_bg_hover)
    btn_press = _hex(p.button_bg_pressed)
    sel = _hex(p.selection)
    sel_fg = _hex(p.text_inverse)
    muted = _hex(p.text_muted)
    disabled_fg = _hex(p.text_disabled)
    overlay = _hex(p.overlay_bg)
    alt_bg = _hex(p.panel_bg_alt)
    accent = _hex(p.accent)
    canvas = _hex(p.canvas_bg)
    radius_btn = m.button_radius_px
    radius_panel = m.panel_radius_px
    border_w = m.border_px
    sp_xs = m.spacing_xs
    sp_sm = m.spacing_sm
    sp_md = m.spacing_md
    sp_lg = m.spacing_lg
    ui_family = t.ui_family
    ui_pt = t.ui_size_pt
    small_pt = t.small_size_pt
    mono_family = t.mono_family
    mono_pt = t.mono_size_pt

    return f"""
/* ============================================================
   Generated by ported.lks_utils.gui_qt.theme.stylesheet_generator
   Theme: {theme.name}
   ============================================================ */

/* --- Base -------------------------------------------------- */
QWidget {{
    background-color: #{bg};
    color: #{fg};
    font-family: "{ui_family}";
    font-size: {ui_pt}pt;
    border: none;
    outline: none;
}}

/* --- Buttons ----------------------------------------------- */
QPushButton {{
    background-color: #{btn_bg};
    color: #{btn_fg};
    border: {border_w}px solid #{border};
    border-radius: {radius_btn}px;
    padding: {sp_xs}px {sp_md}px;
    min-height: {sp_lg}px;
}}
QPushButton:hover {{
    background-color: #{btn_hover};
}}
QPushButton:pressed {{
    background-color: #{btn_press};
}}
QPushButton:disabled {{
    color: #{disabled_fg};
    background-color: #{alt_bg};
    border-color: #{border};
}}

/* --- Input fields ------------------------------------------ */
QLineEdit, QTextEdit, QPlainTextEdit {{
    background-color: #{input_bg};
    color: #{input_fg};
    border: {border_w}px solid #{input_border};
    border-radius: {radius_btn}px;
    padding: {sp_xs}px {sp_sm}px;
    selection-background-color: #{sel};
    selection-color: #{sel_fg};
}}
QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus {{
    border-color: #{accent};
}}
QLineEdit:disabled, QTextEdit:disabled, QPlainTextEdit:disabled {{
    color: #{disabled_fg};
    background-color: #{alt_bg};
}}

/* --- ComboBox / SpinBox ------------------------------------ */
QComboBox, QSpinBox, QDoubleSpinBox {{
    background-color: #{input_bg};
    color: #{input_fg};
    border: {border_w}px solid #{input_border};
    border-radius: {radius_btn}px;
    padding: {sp_xs}px {sp_sm}px;
    min-height: {sp_lg}px;
}}
QComboBox:hover, QSpinBox:hover, QDoubleSpinBox:hover {{
    border-color: #{accent};
}}
QComboBox::drop-down {{
    border: none;
    width: {sp_lg}px;
}}
QComboBox QAbstractItemView {{
    background-color: #{input_bg};
    color: #{input_fg};
    selection-background-color: #{sel};
    selection-color: #{sel_fg};
    border: {border_w}px solid #{input_border};
}}

/* Some Qt styles host combo popups in top-level item views/frames.
   Keep popup lists opaque regardless of host style behavior. */
QAbstractItemView {{
    background-color: #{input_bg};
    color: #{input_fg};
    border: {border_w}px solid #{input_border};
    selection-background-color: #{sel};
    selection-color: #{sel_fg};
}}

QListView {{
    background-color: #{input_bg};
    color: #{input_fg};
    border: {border_w}px solid #{input_border};
}}

/* --- CheckBox / RadioButton -------------------------------- */
QCheckBox, QRadioButton {{
    color: #{fg};
    spacing: {sp_sm}px;
}}
QCheckBox:disabled, QRadioButton:disabled {{
    color: #{disabled_fg};
}}

/* --- GroupBox --------------------------------------------- */
QGroupBox {{
    color: #{fg};
    border: {border_w}px solid #{border};
    border-radius: {radius_panel}px;
    margin-top: {sp_md}px;
    padding-top: {sp_md}px;
}}
QGroupBox::title {{
    subcontrol-origin: margin;
    left: {sp_sm}px;
    color: #{muted};
    font-size: {small_pt}pt;
}}

/* --- Menu -------------------------------------------------- */
QMenu {{
    background-color: #{overlay};
    color: #{fg};
    border: {border_w}px solid #{border};
    border-radius: {radius_panel}px;
    padding: {sp_xs}px 0px;
}}
QMenu::item {{
    padding: {sp_xs}px {sp_lg}px;
}}
QMenu::item:selected {{
    background-color: #{sel};
    color: #{sel_fg};
}}
QMenu::separator {{
    height: {border_w}px;
    background: #{border};
    margin: {sp_xs}px 0px;
}}

/* --- MenuBar ---------------------------------------------- */
QMenuBar {{
    background-color: #{bg};
    color: #{fg};
    border-bottom: {border_w}px solid #{border};
}}
QMenuBar::item:selected {{
    background-color: #{sel};
    color: #{sel_fg};
}}

/* --- ToolBar ---------------------------------------------- */
QToolBar {{
    background-color: #{bg};
    border-bottom: {border_w}px solid #{border};
    spacing: {sp_xs}px;
    padding: {sp_xs}px;
}}
QToolBar::separator {{
    background: #{border};
    width: {border_w}px;
    margin: {sp_xs}px {sp_sm}px;
}}

/* --- StatusBar -------------------------------------------- */
QStatusBar {{
    background-color: #{bg};
    color: #{muted};
    border-top: {border_w}px solid #{border};
    font-size: {small_pt}pt;
}}

/* --- Tabs -------------------------------------------------- */
QTabWidget::pane {{
    border: {border_w}px solid #{border};
    background-color: #{bg};
}}
QTabBar::tab {{
    background-color: #{alt_bg};
    color: #{muted};
    border: {border_w}px solid #{border};
    padding: {sp_xs}px {sp_md}px;
    border-bottom: none;
    border-top-left-radius: {radius_btn}px;
    border-top-right-radius: {radius_btn}px;
}}
QTabBar::tab:selected {{
    background-color: #{bg};
    color: #{fg};
}}
QTabBar::tab:hover:!selected {{
    color: #{fg};
}}

/* --- ScrollBar -------------------------------------------- */
QScrollBar:vertical {{
    background: #{alt_bg};
    width: {sp_md + sp_xs}px;
    border-radius: {radius_btn}px;
}}
QScrollBar::handle:vertical {{
    background: #{muted};
    min-height: {sp_lg}px;
    border-radius: {radius_btn}px;
    margin: {sp_xs}px;
}}
QScrollBar::handle:vertical:hover {{
    background: #{fg};
}}
QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
    height: 0px;
}}
QScrollBar:horizontal {{
    background: #{alt_bg};
    height: {sp_md + sp_xs}px;
    border-radius: {radius_btn}px;
}}
QScrollBar::handle:horizontal {{
    background: #{muted};
    min-width: {sp_lg}px;
    border-radius: {radius_btn}px;
    margin: {sp_xs}px;
}}
QScrollBar::handle:horizontal:hover {{
    background: #{fg};
}}
QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
    width: 0px;
}}

/* --- Tree / List / Table views ----------------------------- */
QTreeView, QListView, QTableView {{
    background-color: #{canvas};
    color: #{fg};
    alternate-background-color: #{alt_bg};
    border: {border_w}px solid #{border};
    gridline-color: #{border};
    selection-background-color: #{sel};
    selection-color: #{sel_fg};
}}
QTreeView::item:hover, QListView::item:hover, QTableView::item:hover {{
    background-color: #{alt_bg};
}}
QHeaderView::section {{
    background-color: #{alt_bg};
    color: #{muted};
    border: none;
    border-right: {border_w}px solid #{border};
    border-bottom: {border_w}px solid #{border};
    padding: {sp_xs}px {sp_sm}px;
    font-size: {small_pt}pt;
}}

/* --- DockWidget ------------------------------------------- */
QDockWidget {{
    titlebar-close-icon: none;
    titlebar-normal-icon: none;
    color: #{fg};
    border: {border_w}px solid #{border};
}}
QDockWidget::title {{
    background-color: #{alt_bg};
    padding: {sp_xs}px {sp_sm}px;
    border-bottom: {border_w}px solid #{border};
}}

/* --- Tooltip ---------------------------------------------- */
QToolTip {{
    background-color: #{overlay};
    color: #{fg};
    border: {border_w}px solid #{border};
    padding: {sp_xs}px {sp_sm}px;
    border-radius: {radius_btn}px;
    font-size: {small_pt}pt;
    opacity: 230;
}}

/* --- Slider ----------------------------------------------- */
QSlider::groove:horizontal {{
    background: #{alt_bg};
    height: {border_w * 2}px;
    border-radius: {border_w}px;
}}
QSlider::handle:horizontal {{
    background: #{accent};
    width: {sp_md}px;
    height: {sp_md}px;
    margin: -{sp_xs}px 0;
    border-radius: {sp_xs + 2}px;
}}
QSlider::sub-page:horizontal {{
    background: #{accent};
    border-radius: {border_w}px;
}}

/* --- Monospace / code fields ------------------------------- */
QTextEdit[readOnly="true"] {{
    font-family: "{mono_family}";
    font-size: {mono_pt}pt;
}}
""".strip()


__all__ = ["theme_to_qss"]
