"""
CoatMenu - how a list becomes a real menu entry.

Two things have to exist for a list to be reachable from a hotkey:

1. **a thin launcher script** - ``actions/lists/<slug>.py``. 3DCoat menu items
   point at a *file*, and one file cannot know which list it belongs to, so each
   list gets its own generated wrapper (this is how LKS does it too).
2. **a menu item** - ``Scripts/ExtraMenuItems/CoatMenu.xml`` (persistent, read at
   startup) *and* a runtime ``coat.ui.insertInMenu`` call (visible immediately).

Everything here is pure filesystem work with explicit paths, so it runs both
inside 3DCoat and from the standalone installer.
"""
from __future__ import annotations

import os

from core.config import MenuConfig

MAIN_MENU_ID = "CoatMenu_Show"
MAIN_MENU_LABEL = "Show CoatMenu"
MAIN_SCRIPT_NAME = "CoatMenu_Show.py"

EDITOR_MENU_ID = "CoatMenu_Editor"
EDITOR_MENU_LABEL = "Edit lists"
EDITOR_SCRIPT_NAME = "CoatMenu_Editor.py"

_ENTRY_SCRIPT = '''"""CoatMenu list launcher - generated by CoatMenu, do not edit.

List: {name} (slug: {slug})
Regenerate from the CoatMenu editor; edits here are overwritten.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(os.path.dirname(_HERE))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from core.log import log  # noqa: E402
from core.show import show_list  # noqa: E402


def main() -> None:
    log("menu item: list {slug}")
    show_list({slug!r}, script_path=os.path.abspath(__file__))


main()

# Re-runnable on the next click.
if not hasattr(sys, "_coatmenu_modules_to_clear"):
    sys._coatmenu_modules_to_clear = set()
sys._coatmenu_modules_to_clear.add(__name__)
'''

_MENU_ENTRY = """\t<ExtraMenuItem>
\t\t<MenuPath>Scripts</MenuPath>
\t\t<MenuItem>{menu_id}</MenuItem>
\t\t<inRoom></inRoom>
\t\t<inSection></inSection>
\t\t<Command>script:{script}</Command>
\t</ExtraMenuItem>
"""

_MENU_XML = "<ClassArray.ExtraMenuItem>\n{entries}</ClassArray.ExtraMenuItem>\n"


def _posix(path: str) -> str:
    return str(path).replace("\\", "/")


def entry_script_path(entry_scripts_dir: str, slug: str) -> str:
    return os.path.join(entry_scripts_dir, f"{slug}.py")


def write_entry_scripts(config: MenuConfig, entry_scripts_dir: str) -> tuple[list[str], list[str]]:
    """(re)write one launcher per list; delete launchers for gone lists.

    Returns ``(written, removed)`` absolute paths.
    """
    os.makedirs(entry_scripts_dir, exist_ok=True)
    wanted = {lst.slug: lst for lst in config.lists}
    written: list[str] = []
    removed: list[str] = []

    for slug, lst in wanted.items():
        path = entry_script_path(entry_scripts_dir, slug)
        content = _ENTRY_SCRIPT.format(name=lst.name, slug=slug)
        if _read(path) != content:
            with open(path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(content)
            written.append(path)

    for name in os.listdir(entry_scripts_dir):
        if not name.endswith(".py"):
            continue
        slug = name[:-3]
        if slug in wanted or slug == "__init__":
            continue
        path = os.path.join(entry_scripts_dir, name)
        try:
            os.remove(path)
            removed.append(path)
        except OSError:
            pass

    return written, removed


def menu_entries(config: MenuConfig, extension_root: str, entry_scripts_dir: str) -> list[tuple[str, str, str]]:
    """``(menu_id, label, script_path)`` for the main entry, the editor and every list."""
    rows = [
        (
            MAIN_MENU_ID,
            MAIN_MENU_LABEL,
            os.path.join(extension_root, "actions", MAIN_SCRIPT_NAME),
        ),
        (
            EDITOR_MENU_ID,
            EDITOR_MENU_LABEL,
            os.path.join(extension_root, "actions", EDITOR_SCRIPT_NAME),
        ),
    ]
    for lst in config.lists:
        rows.append((lst.hotkey_id, lst.name, entry_script_path(entry_scripts_dir, lst.slug)))
    return rows


def write_menu_xml(config: MenuConfig, extension_root: str, entry_scripts_dir: str, xml_path: str) -> str:
    """Write ``ExtraMenuItems/CoatMenu.xml`` (3DCoat needs absolute paths)."""
    entries = "".join(
        _MENU_ENTRY.format(menu_id=menu_id, script=_posix(script))
        for menu_id, _label, script in menu_entries(config, extension_root, entry_scripts_dir)
    )
    os.makedirs(os.path.dirname(xml_path), exist_ok=True)
    content = _MENU_XML.format(entries=entries)
    with open(xml_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    return xml_path


def sync(config: MenuConfig, extension_root: str, entry_scripts_dir: str, xml_path: str) -> dict:
    """Bring the launcher scripts and the menu XML in line with ``config``."""
    written, removed = write_entry_scripts(config, entry_scripts_dir)
    write_menu_xml(config, extension_root, entry_scripts_dir, xml_path)
    return {
        "lists": len(config.lists),
        "scripts_written": written,
        "scripts_removed": removed,
        "menu_xml": xml_path,
    }


def _read(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return ""
